[package]
name = "calculator-app"
version = "0.1.0"
authors = ["rinz13r <srinivasan.vijayraghavan@iiitb.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
